### ISSUE TITLE
450 Transfer Aborted when trying to upload ~100MB file

### ISSUE THREAD

**Issue by avirtopeanu-ionos** [kardianos/ftps#1]
Hi, I'm trying to store a file, like this:

```
file, err := os.Open(path)
if err != nil {
	return err
}

buff := bufio.NewReader(file)
ctx, cancel := context.WithDeadline(context.Background(), time.Now().Add(600*time.Second))
defer cancel()

c, err := ftps.Dial(ctx, dialOptions)
if err != nil {
	return err
}
fmt.Printf("Connected to %s\n", p.Url)

	err = c.Upload(ctx,  filepath.Base(path), buff)
```
Problem is, for large uploads (~100MB), the upload fails almost instantly. For small files (~4MB), the upload works fine. Any ideas what could cause this? Upload works fine via FileZilla / command line ftp

It is clear that the Context Deadline (600 seconds) is not respected, upload fails in about 10 secs.

Full error: `Error: upload read: failed to read code, got code 450 and message Transfer aborted. Link to file server lost: 450 Transfer aborted. Link to file server lost`

**Comment by kardianos** [comment]
Is it possible to modify ftps_test.go to reproduce this?

**Comment by kardianos** [comment]
Also, do you know what the server FTP software is?

Doing a quick search, looks like the following library https://github.com/lavv17/lftp/issues/621 also encountered this. That issue points to http://www.proftpd.org/docs/contrib/mod_tls.html#TLSSessionTickets for TLS Session Tickets being required on the FTP server. It looks like there is another issue with the same server "ProFTPd" in the rclone forum: https://forum.rclone.org/t/rclone-ftps-explicit-copy-failed-to-copy-update-stor-450-transfer-aborted-link-to-file-server-lost/24721 . That cites:
> Good news, it seems the problem is ProFTPD in version < 1.3.7rc4 when using TLS 1.3 => Rclone has nothing to do with it. With ProFTPD 1.3.7a the data transfer worked. So I checked the changelog of ProFTPD and found that there was a fix for a problem: "Fixed issue with FTPS uploads of large files u…

Concretely, can you try putting a Max TLS1.2 version in the TLSConfig in the Dial?
Thanks.

**Comment by avirtopeanu-ionos** [comment]
Hello! I added `MaxVersion: tls.VersionTLS12,` in tlsConfig and now it works perfectly. Great work on this package, and thank you for your help!

**Comment by JoeyBoolean** [comment]
If anyone is still struggling with this I found a solution that works. You **must** create a ClientSessionCache in the TLSConfig and you **must** set the ServerName in the TLSConfig as well. Here is the DialOptions struct I am using:
```go
ftps.DialOptions{
	Host:        ftpServerAddress,
	Port:        int(ftpPort),
	Username:    ftpUser,
	Passowrd:    ftpPassword,
	ExplicitTLS: true,
	TLSConfig: &tls.Config{
		InsecureSkipVerify: true,
		ClientSessionCache: tls.NewLRUClientSessionCache(32),
		ServerName:         ftpServerAddress, // This can be an IP Address
	},
},
```
